# Top-level configuration
name = "questlog-workers"
compatibility_date = "2024-03-20"
main = "workers/transcribe-audio/index.ts"
compatibility_flags = ["nodejs_compat"]

# Bindings like secrets, vars, kv_namespaces are managed via the dashboard or CLI commands (e.g., wrangler secret put)
# and accessed via the 'env' object in the worker script.
