name = "clerk-user-sync-worker"
main = "src/index.ts"
compatibility_date = "2024-04-03" # Use a recent date

# Define secrets that need to be set in the Cloudflare dashboard
# wrangler secret put CLERK_WEBHOOK_SIGNING_SECRET
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_SERVICE_ROLE_KEY
[vars]
# SUPABASE_URL can often be set here if it's not considered a secret,
# but it's safer practice to treat it as a secret along with the keys.

[secrets]
CLERK_WEBHOOK_SIGNING_SECRET = ""
SUPABASE_URL = "https://mpbvqueyjbqtdfqftqpd.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wYnZxdWV5amJxdGRmcWZ0cXBkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzczMDYzNywiZXhwIjoyMDUzMzA2NjM3fQ.orpXiqUlenocEwAhbWend5rC0f3mXyXb7hg8tW05TtA"
